runtime:
  app_name: distmlApp 
  print_time: True
  master: local
  library_paths:
    - C:\Users\91767\Downloads\blueprint.zip 
  spark_conf:
  #      spark.submit.deployMode: cluster
    spark.executor.instances: 2
    spark.executor.cores: 1
    spark.task.cpus: 1
    spark.executor.memory: 20g
    spark.driver.cores: 4 
    spark.driver.nemory: 64g
    spark.jars: C:\Users\91767\Downloads\spark-tensorflow-connector_2.11-1.15.0.jar 

model_params:
  epochs: 100
  train cnt: 
  eval cnt: 
  log_dir: C:\Users\91767\Downloads\tblogs\fit 
  model_dir: C:\Users\91767\Downloads\tf_regression
  tensorboard: True
  tb_port: 3025 
  model_id: 1611063835
  hpTuning:
    hparamLog_dir: C:\Users\91767\Downloads\tblogs\hparam_tuning
    metrics:
      mse:
        name: MSE
    hparams:
      learning rate:
        name: HP_LEARNING_RATE
        type: Discrete
        values:
          - 0.1
          - 0.01
          - 0.001
      reduceLR_op:
        name: HP_REDUCELR_OP
        type: Discrete
        values:
          - True
          - False
data_paths:
  train_path: C:\Users\91767\Downloads\titanic\train.csv 
  eval_path: C:\Users\91767\Downloads\titanic\train.csv 
  pred_path: C:\Users\91767\Downloads\titanic\test.csv
  export_dir: C:\Users\91767\Downloads\tf_regression_export
  output_dir: C:\Users\91767\Downloads\tf_regression_output